#!/usr/bin/env bash

# echo to stderr
function ercho { printf "%s\n" "$*" >&2; }

IS_NVIDIA_GPU="$(lspci | grep -i nvidia)"

# find maximum and minimum power limits
if [ -z "$IS_NVIDIA_GPU" ]; then
  MINIMUM="$(cat /sys/class/drm/card*/device/hwmon/hwmon*/power1_cap_min | sort -n | tail -n1)"
  MAXIMUM="$(cat /sys/class/drm/card*/device/hwmon/hwmon*/power1_cap_max | sort -n | head -n1)"
  MINIMUM=$((MINIMUM / 1000000))
  MAXIMUM=$((MAXIMUM / 1000000))
else
  MINIMUM="$(nvidia-smi -q -d POWER | sed -nr "s/Min Power Limit.*: ([0-9]+).[0-9]+ W/\1/p" | sed 's/^[[:space:]]*//' | sort -n | tail -n1)"
  MAXIMUM="$(nvidia-smi -q -d POWER | sed -nr "s/Max Power Limit.*: ([0-9]+).[0-9]+ W/\1/p" | sed 's/^[[:space:]]*//' | sort -n | tail -n1)"
fi

function main {
  local limit="$1"
  if [ -z "$limit" ]; then
    # print the current limit
    local curr
    if [ -z "$IS_NVIDIA_GPU" ]; then
      curr="$(cat /sys/class/drm/card*/device/hwmon/hwmon*/power1_cap | sort -n | tail -n1)"
      curr=$((curr / 1000000))
    else
      curr="$(nvidia-smi -q -d POWER | sed -nr "s/Current Power Limit.*: ([0-9]+).[0-9]+ W/\1/p" | sed 's/^[[:space:]]*//' | sort -n | tail -n1)"
    fi
    echo "Current power limit: $curr W"
    exit 0
  fi
  if ((limit < MINIMUM || limit > MAXIMUM)); then
    ercho "Invalid limit: $limit"
    ercho "Valid range: $MINIMUM-$MAXIMUM W"
    exit 1
  fi

  if [ -z "$IS_NVIDIA_GPU" ]; then
    echo "$limit""000000" | tee /sys/class/drm/card*/device/hwmon/hwmon*/power1_cap
  else
    nvidia-smi -pl "$limit"
  fi
}

# check sudo
if [ "$(id -u)" -ne 0 ]; then
  ercho "Please run as root"
  exit 1
fi

main "$@"
